language: perl
matrix:
  include:
    - perl: "5.14"
      env: USE_SYSTEM_PERL=1
    - perl: "5.20"
    - perl: "5.18"
    - perl: "5.16"
    - perl: "5.14"
    - perl: "5.12"
    - perl: "5.10"
    - perl: "5.8"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && perlbrew off || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && sudo apt-get install -qq libx11-dev libfreetype6-dev libxft-dev || true'
 - Xvfb :123 &
 - export DISPLAY=:123
 # Wait until X server is available
 - perl -MIO::Socket::INET -e 'for (1..10) { IO::Socket::INET->new(PeerAddr => "localhost:6123") and exit; sleep 1 }'
 - twm &
 # Wait until window manager is running
 - sleep 2
install:
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq perl-tk || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest --installdeps . || true'
