language: perl
arch:
 - arm64
matrix:
 include:
  - dist: xenial
    env: USE_SYSTEM_PERL=1
    language: minimal
  - dist: bionic
    perl: 5.26
  - dist: focal
    perl: 5.32

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq xvfb twm
 - '[ "$USE_SYSTEM_PERL" != "1" ] && sudo apt-get install -qq libx11-dev libfreetype6-dev libxft-dev || true'
 - Xvfb :123 &
 - export DISPLAY=:123
 # Wait until X server is available
 - perl -MIO::Socket::INET -e 'for (1..10) { IO::Socket::INET->new(PeerAddr => "localhost:6123") and exit; sleep 1 }'
 - twm &
 # Wait until window manager is running
 - sleep 2
install:
 - '[ "$USE_SYSTEM_PERL"  = "1" ] && sudo apt-get install -qq perl-tk || true'
 - '[ "$USE_SYSTEM_PERL" != "1" ] && cpanm --quiet --notest --installdeps . || true'

branches:
 except:
  - /appveyor/
  - /github-actions/
  - /gitlab/
  - /doozer/
